<a href="https://colab.research.google.com/github/Sautramani/Pandas-Numpy/blob/main/Import_and_export_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
# OPENING A LOCAL CSV FILE
df = pd.read_csv('cars.csv')
dog=pd.read_csv('movies.csv')
dog

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [4]:
# OPENING A CSV FILE FROM AN URL(LINK)
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [5]:
# SEP PARAMETER
df=pd.read_csv('movie_titles.tsv')
df
df=pd.read_csv('movie_titles.tsv',sep='\t')
df

,m0,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...
...,...,...,...,...,...,...
611,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
612,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
613,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
614,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
615,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [6]:
#INDEX_COL PARAMETER (KISI BHI COLUMN KO AS A INDEX SET KAR SAKTE HAIN)
df=pd.read_csv('ipl-matches.csv')
df
df=pd.read_csv('ipl-matches.csv',index_col='City')
df

,ID,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
City,,,,,,,,,,,,,,,,,,,
Ahmedabad,1312200,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
Ahmedabad,1312199,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
Kolkata,1312198,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
Kolkata,1312197,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
Mumbai,1304116,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kolkata,335986,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
Mumbai,335985,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
Delhi,335984,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
Chandigarh,335983,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
Bangalore,335982,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [7]:
#HEADER PARAMETER (header parameter in pd.read_csv() tells Pandas which row of the CSV should be treated as the column names.)
df=pd.read_csv('cars.csv', header=1)
df

       Maruti  145500  Diesel           First Owner  450000
0       Skoda  120000  Diesel          Second Owner  370000
1       Honda  140000  Petrol           Third Owner  158000
2     Hyundai  127000  Diesel           First Owner  225000
3      Maruti  120000  Petrol           First Owner  130000
4     Hyundai   45000  Petrol           First Owner  440000
...       ...     ...     ...                   ...     ...
8122  Hyundai  110000  Petrol           First Owner  320000
8123  Hyundai  119000  Diesel  Fourth & Above Owner  135000
8124   Maruti  120000  Diesel           First Owner  382000
8125     Tata   25000  Diesel           First Owner  290000
8126     Tata   25000  Diesel           First Owner  290000

[8127 rows x 5 columns]

In [8]:
#Usecols parameter (DATASET SE JO JO COLUMNS CHAHIYE UNKO CHAANTH LO)
df=pd.read_csv('ipl-matches.csv', usecols=['City','Venue','Team1'])
df

,City,Team1,Venue
0,Ahmedabad,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad"
1,Ahmedabad,Royal Challengers Bangalore,"Narendra Modi Stadium, Ahmedabad"
2,Kolkata,Royal Challengers Bangalore,"Eden Gardens, Kolkata"
3,Kolkata,Rajasthan Royals,"Eden Gardens, Kolkata"
4,Mumbai,Sunrisers Hyderabad,"Wankhede Stadium, Mumbai"
...,...,...,...
945,Kolkata,Kolkata Knight Riders,Eden Gardens
946,Mumbai,Mumbai Indians,Wankhede Stadium
947,Delhi,Delhi Daredevils,Feroz Shah Kotla
948,Chandigarh,Kings XI Punjab,"Punjab Cricket Association Stadium, Mohali"
949,Bangalore,Royal Challengers Bangalore,M Chinnaswamy Stadium

In [9]:
 #SKIPROWS/nrows PARAMETER
 df=pd.read_csv('ipl-matches.csv',skiprows=[947,948]) #kuch particular rows agar remove karni ho
 df
 df=pd.read_csv('ipl-matches.csv',nrows=150) #Keval kuch hi rows chahiye agar
 df

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,1216536,NaN,2020-10-29,2020/21,49,Kolkata Knight Riders,Chennai Super Kings,Dubai International Cricket Stadium,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,6.0,NaN,RD Gaikwad,"['Shubman Gill', 'N Rana', 'SP Narine', 'RK Si...","['SR Watson', 'RD Gaikwad', 'AT Rayudu', 'MS D...",C Shamshuddin,RK Illingworth
146,1216499,Abu Dhabi,2020-10-28,2020/21,48,Royal Challengers Bangalore,Mumbai Indians,Sheikh Zayed Stadium,Mumbai Indians,field,N,Mumbai Indians,Wickets,5.0,NaN,SA Yadav,"['JR Philippe', 'D Padikkal', 'V Kohli', 'AB d...","['Q de Kock', 'Ishan Kishan', 'SA Yadav', 'SS ...",UV Gandhe,CB Gaffaney
147,1216524,NaN,2020-10-27,2020/21,47,Sunrisers Hyderabad,Delhi Capitals,Dubai International Cricket Stadium,Delhi Capitals,field,N,Sunrisers Hyderabad,Runs,88.0,NaN,WP Saha,"['DA Warner', 'WP Saha', 'MK Pandey', 'KS Will...","['AM Rahane', 'S Dhawan', 'MP Stoinis', 'SO He...",AK Chaudhary,Nitin Menon
148,1216520,NaN,2020-10-26,2020/21,46,Kolkata Knight Riders,Kings XI Punjab,Sharjah Cricket Stadium,Kings XI Punjab,field,N,Kings XI Punjab,Wickets,8.0,NaN,CH Gayle,"['Shubman Gill', 'N Rana', 'RA Tripathi', 'KD ...","['KL Rahul', 'Mandeep Singh', 'CH Gayle', 'N P...",KN Ananthapadmanabhan,RK Illingworth
149,1216541,Abu Dhabi,2020-10-25,2020/21,45,Mumbai Indians,Rajasthan Royals,Sheikh Zayed Stadium,Mumbai Indians,bat,N,Rajasthan Royals,Wickets,8.0,NaN,BA Stokes,"['Ishan Kishan', 'Q de Kock', 'SA Yadav', 'SS ...","['RV Uthappa', 'BA Stokes', 'SPD Smith', 'SV S...",UV Gandhe,VK Sharma

In [10]:
#ENCODING PARAMETER
pd.read_csv('zomato.csv',encoding='latin-1')

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [11]:
# SKIP BAD LINES
pd.read_csv('zomato.csv', sep=';', encoding="latin-1", on_bad_lines='skip', engine='python')

     Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0     6317637,Le Petit Souffle,162,Makati City,"Thir...
1     6304287,Izakaya Kikufuji,162,Makati City,"Litt...
2     6300002,Heat - Edsa Shangri-La,162,Mandaluyong...
3     6318506,Ooma,162,Mandaluyong City,"Third Floor...
4     6314302,Sambo Kojin,162,Mandaluyong City,"Thir...
...                                                 ...
9552  5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô ...
9553  5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu...
9554  5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahal...
9555  5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôm...
9556  5927402,Walter's Coffee Roastery,208,ÛÁstanbul...

[9557 rows x 1 columns]

In [12]:
#HANDLING DATATYPES
df=pd.read_csv('ipl-matches.csv',dtype={'ID':float}).info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    float64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(2), object(18)
memory usage: 148.6+ KB

In [13]:
#HANDLING DATES
pd.read_csv('ipl-matches.csv', parse_dates=['Date']).info() #NOW WE CAN APPLY FILTERS ON DATETIME64 DATATYPE AS IT IS NOT STRING NOW

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    datetime64[ns]
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(17)
memory usage: 148.6+ KB

In [14]:
# CONVERTERS (converters ka use CSV se data read karte time kisi particular column ke har value par apna function apply karne ke liye hota hai.)
def rename(name):
    if name == "Delhi Daredevils":
      return "DC"
    if name == "Royal Challengers Bangalore":
      return "RCB"
    else:
        return name

In [15]:
rename("Royal Challengers Bangalore")

'RCB'

In [16]:
pd.read_csv('ipl-matches.csv',converters={'Team1':rename})

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,RCB,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,RCB,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,DC,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,RCB,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [17]:
#LOADING A HUGE DATASET IN CHUNKS
dfs=pd.read_csv('aug_train.csv',chunksize=5000)
for chunks in dfs:
  print(chunks)

      enrollee_id      city  city_development_index  gender  \
0            8949  city_103                   0.920    Male
1           29725   city_40                   0.776    Male
2           11561   city_21                   0.624     NaN
3           33241  city_115                   0.789     NaN
4             666  city_162                   0.767    Male
...           ...       ...                     ...     ...
4995         7892   city_21                   0.624  Female
4996        19768   city_21                   0.624    Male
4997        33180   city_16                   0.910    Male
4998        13215  city_103                   0.920  Female
4999         2386   city_21                   0.624    Male

          relevent_experience enrolled_university education_level  \
0     Has relevent experience       no_enrollment        Graduate
1      No relevent experience       no_enrollment        Graduate
2      No relevent experience    Full time course        Graduate
3      No relevent experience                 NaN        Graduate
4     Has relevent experience       no_enrollment         Masters
...                       ...                 ...             ...
4995  Has relevent experience       no_enrollment        Graduate
4996   No relevent experience       no_enrollment        Graduate
4997   No relevent experience       no_enrollment     High School
4998  Has relevent experience       no_enrollment        Graduate
4999  Has relevent experience       no_enrollment        Graduate

     major_discipline experience company_size    company_type last_new_job  \
0                STEM        >20          NaN             NaN            1
1                STEM         15        50-99         Pvt Ltd           >4
2                STEM          5          NaN             NaN        never
3     Business Degree         <1          NaN         Pvt Ltd        never
4                STEM        >20        50-99  Funded Startup            4
...               ...        ...          ...             ...          ...
4995             STEM          3      100-500             NaN            1
4996             STEM          3      100-500         Pvt Ltd            1
4997              NaN        >20    5000-9999         Pvt Ltd           >4
4998             STEM         10       10000+         Pvt Ltd           >4
4999             STEM          2    5000-9999         Pvt Ltd            2

      training_hours  target
0                 36     1.0
1                 47     0.0
2                 83     0.0
3                 52     1.0
4                  8     0.0
...              ...     ...
4995             114     1.0
4996              64     1.0
4997              89     0.0
4998              20     1.0
4999              16     0.0

[5000 rows x 14 columns]
      enrollee_id      city  city_development_index  gender  \
5000        18582   city_83                   0.923    Male
5001        25222  city_159                   0.843     NaN
5002         5697   city_61                   0.913  Female
5003         5172   city_21                   0.624    Male
5004         1815   city_27                   0.848    Male
...           ...       ...                     ...     ...
9995        27017   city_73                   0.754   Other
9996         7559  city_103                   0.920    Male
9997        12332  city_103                   0.920    Male
9998         3974  city_102                   0.804    Male
9999        13267   city_75                   0.939    Male

          relevent_experience enrolled_university education_level  \
5000  Has relevent experience       no_enrollment         Masters
5001  Has relevent experience       no_enrollment        Graduate
5002  Has relevent experience       no_enrollment        Graduate
5003   No relevent experience    Full time course        Graduate
5004  Has relevent experience       no_enrollment         Masters
...                       ...                 ...             ...
9995   No relevent experience       no_enrollment        Graduate
9996  Has relevent experience       no_enrollment        Graduate
9997   No relevent experience    Full time course        Graduate
9998  Has relevent experience    Full time course         Masters
9999  Has relevent experience       no_enrollment        Graduate

     major_discipline experience company_size   company_type last_new_job  \
5000             STEM          9       10000+        Pvt Ltd            4
5001             STEM          7          <10        Pvt Ltd            1
5002             STEM        >20      100-500            NaN            1
5003             STEM          3          NaN            NaN        never
5004             STEM         18       10000+        Pvt Ltd           >4
...               ...        ...          ...            ...          ...
9995             STEM         <1          NaN            NaN        never
9996             STEM          4        50-99        Pvt Ltd            1
9997             STEM          2          NaN            NaN            1
9998             STEM          7       10000+  Public Sector            1
9999             STEM          9          NaN        Pvt Ltd            1

      training_hours  target
5000             170     0.0
5001             107     0.0
5002               9     0.0
5003              38     1.0
5004              17     1.0
...              ...     ...
9995               7     0.0
9996              42     0.0
9997              12     0.0
9998               2     1.0
9999              40     0.0

[5000 rows x 14 columns]
       enrollee_id      city  city_development_index  gender  \
10000        23427   city_24                   0.698     NaN
10001        17605   city_50                   0.896     NaN
10002        20912   city_73                   0.754     NaN
10003        13948  city_114                   0.926    Male
10004        15205  city_160                   0.920    Male
...            ...       ...                     ...     ...
14995         1305  city_103                   0.920    Male
14996        10310  city_103                   0.920  Female
14997        10689   city_21                   0.624     NaN
14998          605   city_16                   0.910    Male
14999        14587   city_16                   0.910    Male

           relevent_experience enrolled_university education_level  \
10000   No relevent experience                 NaN     High School
10001   No relevent experience       no_enrollment        Graduate
10002   No relevent experience    Full time course        Graduate
10003   No relevent experience       no_enrollment             Phd
10004   No relevent experience    Full time course     High School
...                        ...                 ...             ...
14995  Has relevent experience       no_enrollment        Graduate
14996  Has relevent experience       no_enrollment         Masters
14997  Has relevent experience    Full time course        Graduate
14998  Has relevent experience       no_enrollment        Graduate
14999  Has relevent experience       no_enrollment         Masters

      major_discipline experience company_size         company_type  \
10000              NaN          8          NaN                  NaN
10001             STEM        >20          NaN                  NaN
10002             STEM          5          NaN                  NaN
10003             STEM        >20       10000+              Pvt Ltd
10004              NaN          7      100-500              Pvt Ltd
...                ...        ...          ...                  ...
14995             Arts          9          <10                  NGO
14996             STEM         15    1000-4999              Pvt Ltd
14997            Other          5      100-500  Early Stage Startup
14998             STEM         11    5000-9999              Pvt Ltd
14999             STEM        >20        50-99              Pvt Ltd

      last_new_job  training_hours  target
10000        never              63     0.0
10001        never              10     0.0
10002        never              46     0.0
10003            1              18     0.0
10004            1              55     0.0
...            ...             ...     ...
14995            1              37     0.0
14996            3              39     0.0
14997            2              85     1.0
14998           >4               4     0.0
14999            1              14     0.0

[5000 rows x 14 columns]
       enrollee_id      city  city_development_index gender  \
15000         6178  city_103                   0.920    NaN
15001        27557   city_75                   0.939   Male
15002        27751  city_160                   0.920   Male
15003        11186  city_103                   0.920   Male
15004         1600  city_150                   0.698   Male
...            ...       ...                     ...    ...
19153         7386  city_173                   0.878   Male
19154        31398  city_103                   0.920   Male
19155        24576  city_103                   0.920   Male
19156         5756   city_65                   0.802   Male
19157        23834   city_67                   0.855    NaN

           relevent_experience enrolled_university education_level  \
15000  Has relevent experience       no_enrollment        Graduate
15001  Has relevent experience       no_enrollment        Graduate
15002  Has relevent experience       no_enrollment        Graduate
15003   No relevent experience       no_enrollment        Graduate
15004  Has relevent experience       no_enrollment        Graduate
...                        ...                 ...             ...
19153   No relevent experience       no_enrollment        Graduate
19154  Has relevent experience       no_enrollment        Graduate
19155  Has relevent experience       no_enrollment        Graduate
19156  Has relevent experience       no_enrollment     High School
19157   No relevent experience       no_enrollment  Primary School

      major_discipline experience company_size    company_type last_new_job  \
15000             Arts          2        50-99  Funded Startup            1
15001             STEM          6          NaN   Public Sector            1
15002             STEM          9        50-99         Pvt Ltd            1
15003             STEM         15          NaN             NaN           >4
15004             STEM         10          <10         Pvt Ltd            1
...                ...        ...          ...             ...          ...
19153       Humanities         14          NaN             NaN            1
19154             STEM         14          NaN             NaN            4
19155             STEM        >20        50-99         Pvt Ltd            4
19156              NaN         <1      500-999         Pvt Ltd            2
19157              NaN          2          NaN             NaN            1

       training_hours  target
15000              51     0.0
15001              12     1.0
15002               9     0.0
15003             156     0.0
15004              14     0.0
...               ...     ...
19153              42     1.0
19154              52     1.0
19155              44     0.0
19156              97     0.0
19157             127     0.0

[4158 rows x 14 columns]

In [18]:
# Using a for loop and enumerate to print only the 3rd chunk (index 2)
dfs = pd.read_csv('aug_train.csv', chunksize=5000)

for index, chunk in enumerate(dfs):
    if index == 2:
        display(chunk)
        break

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
10000,23427,city_24,0.698,NaN,No relevent experience,NaN,High School,NaN,8,NaN,NaN,never,63,0.0
10001,17605,city_50,0.896,NaN,No relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,never,10,0.0
10002,20912,city_73,0.754,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,46,0.0
10003,13948,city_114,0.926,Male,No relevent experience,no_enrollment,Phd,STEM,>20,10000+,Pvt Ltd,1,18,0.0
10004,15205,city_160,0.920,Male,No relevent experience,Full time course,High School,NaN,7,100-500,Pvt Ltd,1,55,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,1305,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,Arts,9,<10,NGO,1,37,0.0
14996,10310,city_103,0.920,Female,Has relevent experience,no_enrollment,Masters,STEM,15,1000-4999,Pvt Ltd,3,39,0.0
14997,10689,city_21,0.624,NaN,Has relevent experience,Full time course,Graduate,Other,5,100-500,Early Stage Startup,2,85,1.0
14998,605,city_16,0.910,Male,Has relevent experience,no_enrollment,Graduate,STEM,11,5000-9999,Pvt Ltd,>4,4,0.0
14999,14587,city_16,0.910,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Pvt Ltd,1,14,0.0

In [19]:
#IMPORT DATA FROM EXCEL FILES
pd.read_excel('output.xlsx')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Excel Sample Data,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Project Management Data,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Project Name,Task Name,Assigned to,Start Date,Days Required,End Date,Progress
5,NaN,Marketing,Market Research,Alice,2024-01-01 00:00:00,13,2024-01-14 00:00:00,0.78
6,NaN,Marketing,Content Creation,Bob,2024-01-14 00:00:00,14,2024-01-28 00:00:00,1
7,NaN,Marketing,Social Media Planning,Charlie,2024-01-28 00:00:00,22,2024-02-19 00:00:00,0.45
8,NaN,Marketing,Campaign Analysis,Daisy,2024-02-18 00:00:00,25,2024-03-14 00:00:00,0
9,NaN,Product Dev,Prototype Development,Ethan,2024-01-02 00:00:00,18,2024-01-20 00:00:00,1
10,NaN,Product Dev,Quality Assurance,Fiona,2024-01-20 00:00:00,10,2024-01-30 00:00:00,0.78
11,NaN,Product Dev,User Interface Design,Gabriel,2024-02-04 00:00:00,25,2024-02-29 00:00:00,0
12,NaN,Customer Svc,Service Improvement,Hannah,2024-02-01 00:00:00,22,2024-02-23 00:00:00,1
13,NaN,Customer Svc,Ticket Resolution,Ian,2024-02-24 00:00:00,25,2024-03-20 00:00:00,1
14,NaN,Customer Svc,Customer Feedback,Julia,2024-03-21 00:00:00,30,2024-04-20 00:00:00,0
15,NaN,Financial,Budget Analysis,Kevin,2024-02-02 00:00:00,22,2024-02-24 00:00:00,0.1
16,NaN,Financial,Financial Reporting,Mark,2024-02-13 00:00:00,21,2024-02-09 00:00:00,0.78
17,NaN,Financial,Investment Planning,Mark,2024-03-19 00:00:00,25,2024-04-13 00:00:00,1
18,NaN,Research,Market Trends Analysis,Nathan,2024-01-02 00:00:00,23,2024-01-25 00:00:00,0.5
19,NaN,Research,Data Collection,Olivia,2024-01-26 00:00:00,32,2024-02-27 00:00:00,0
20,NaN,Research,Research Paper Writing,Peter,2024-02-28 00:00:00,27,2024-03-26 00:00:00,0
21,NaN,Development,Software Development,Quinn,2024-01-02 00:00:00,36,2024-02-07 00:00:00,1
22,NaN,Development,Feature Enhancement,Rachel,2024-02-08 00:00:00,34,2024-03-13 00:00:00,0
23,NaN,Development,Code Review,Sam,2024-03-14 00:00:00,30,2024-04-13 00:00:00,0
24,NaN,Production,Manufacturing,Tim,2024-01-03 00:00:00,47,2024-02-19 00:00:00,0.3
25,NaN,Production,Quality Control,Ursula,2024-02-17 00:00:00,27,2024-03-15 00:00:00,0
26,NaN,Production,Packaging Design,Victor,2024-03-14 00:00:00,22,2024-04-05 00:00:00,0
27,NaN,Sales,Lead Generation,Wendy,2024-01-03 00:00:00,60,2024-03-03 00:00:00,0.7
28,NaN,Sales,Client Meetings,Xavier,2024-01-06 00:00:00,20,2024-01-26 00:00:00,0.78
29,NaN,Sales,Contract Negotiation,Yvette,2024-02-03 00:00:00,35,2024-03-09 00:00:00,0
30,NaN,Support,Technical Support,Zoe,2024-01-01 00:00:00,25,2024-01-26 00:00:00,1
31,NaN,Support,Bug Fixes,Aaron,2024-01-27 00:00:00,31,2024-02-27 00:00:00,1
32,NaN,Support,Software Updates,Bella,2024-03-02 00:00:00,22,2024-03-24 00:00:00,0
33,NaN,Operations,Process Optimization,Calvin,2024-01-03 00:00:00,30,2024-02-02 00:00:00,0.4
34,NaN,Operations,Inventory Management,Diane,2024-02-03 00:00:00,25,2024-02-28 00:00:00,0
35,NaN,Operations,Facility Maintenance,Edward,2024-02-29 00:00:00,20,2024-03-20 00:00:00,0
36,NaN,Consulting,Strategic Planning,Fiona,2024-01-02 00:00:00,35,2024-02-06 00:00:00,0.6
37,NaN,Consulting,Market Expansion,Gary,2024-02-02 00:00:00,32,2024-03-05 00:00:00,0
38,NaN,Consulting,Client Advisory,Helen,2024-03-06 00:00:00,25,2024-03-31 00:00:00,0
39,NaN,Training,Employee Training,Isaac,2024-01-04 00:00:00,27,2024-01-31 00:00:00,0.8
40,NaN,Training,Certification Programs,Jane,2024-01-28 00:00:00,30,2024-02-27 00:00:00,0
41,NaN,Training,Skill Development,Kyle,2024-02-28 00:00:00,22,2024-03-21 00:00:00,0
42,NaN,Events,Event Planning,Laura,2024-01-03 00:00:00,25,2024-01-28 00:00:00,0.3
43,NaN,Events,Conference Management,Mike,2024-02-03 00:00:00,20,2024-02-23 00:00:00,0
44,NaN,Events,Sponsorship Coordinatio,n Nancy,2024-02-24 00:00:00,35,2024-03-30 00:00:00,0
45,NaN,Logistics,Supply Chain Management,Oscar,2024-01-03 00:00:00,25,2024-01-28 00:00:00,0.5
46,NaN,Logistics,Transportation Planning,Patricia,2024-01-29 00:00:00,30,2024-02-28 00:00:00,1
47,NaN,Logistics,Inventory Optimization,Quentin,2024-03-29 00:00:00,20,2024-04-18 00:00:00,0
48,NaN,Engineering,Product Design,Rachel,2024-01-02 00:00:00,25,2024-01-27 00:00:00,0.2
49,NaN,Engineering,System Integration,Sam,2024-02-02 00:00:00,22,2024-02-24 00:00:00,0
50,NaN,Engineering,Prototype Testing,Tom,2024-02-23 00:00:00,27,2024-03-21 00:00:00,0

In [20]:
#IMPORT DATA FROM TEXT FILES
pd.read_csv('multilang.txt',sep='\t')

                               English: Hello, world!
0                                          中文: 你好，世界！
1                              Español: ¡Hola, mundo!
2                               Русский: Привет, мир!
3                                      日本語: こんにちは、世界！
4                                     한국어: 안녕하세요, 세계！
5                       Français: Bonjour, le monde !
6                               Deutsch: Hallo, Welt!
7                              Italiano: Ciao, mondo!
8                              Português: Olá, mundo!
9                              हिंदी: नमस्ते, दुनिया!
10                            العربية: مرحبا بالعالم!
11  This sample TXT file is provided by Sample-Fil...

In [21]:
#IMPORT DATA FROM JSON FILES
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [22]:
pd.read_json('https://dog.ceo/api/breeds/list/all')

                 message   status
affenpinscher         []  success
african           [wild]  success
airedale              []  success
akita                 []  success
appenzeller           []  success
...                  ...      ...
vizsla                []  success
waterdog       [spanish]  success
weimaraner            []  success
whippet               []  success
wolfhound        [irish]  success

[108 rows x 2 columns]

In [23]:
#IMPORT DATA FROM SQL FILES
!pip install mysql.connector
import mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 97.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py) ... done
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-linux_x86_64.whl size=248031 sha256=a2b4a3257a07845e61f1c409716bc5ad1345e2fb8755ad82b868460140bcc2fb
  Stored in directory: /root/.cache/pip/wheels/4e/c1/23/9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

# EXPORT DATASET AS CSV FILE

In [24]:
df=pd.read_csv('ipl-matches.csv')
df=df.groupby('Team1')['Margin'].sum().reset_index()
df.to_csv('neww.csv',index=False)#AB NEW CSV FILE BAN GAYI PURANI ipl-matches WALI CSV FILE KI HELP SE
pd.read_csv('neww.csv')

                          Team1  Margin
0           Chennai Super Kings  1960.0
1               Deccan Chargers   552.0
2                Delhi Capitals   476.0
3              Delhi Daredevils  1464.0
4                 Gujarat Lions   148.0
5                Gujarat Titans   145.0
6               Kings XI Punjab  1643.0
7          Kochi Tuskers Kerala   137.0
8         Kolkata Knight Riders  1555.0
9          Lucknow Super Giants   174.0
10               Mumbai Indians  1977.0
11                Pune Warriors   357.0
12                 Punjab Kings   247.0
13             Rajasthan Royals  1348.0
14       Rising Pune Supergiant   192.0
15      Rising Pune Supergiants    53.0
16  Royal Challengers Bangalore  2449.0
17          Sunrisers Hyderabad  1020.0

# EXPORT DATASET AS EXCEL **FILE**

In [25]:
df=pd.read_csv('ipl-matches.csv')
df=df.groupby('Team1')['Margin'].sum().reset_index()
df.to_excel('new2.xlsx')
df

                          Team1  Margin
0           Chennai Super Kings  1960.0
1               Deccan Chargers   552.0
2                Delhi Capitals   476.0
3              Delhi Daredevils  1464.0
4                 Gujarat Lions   148.0
5                Gujarat Titans   145.0
6               Kings XI Punjab  1643.0
7          Kochi Tuskers Kerala   137.0
8         Kolkata Knight Riders  1555.0
9          Lucknow Super Giants   174.0
10               Mumbai Indians  1977.0
11                Pune Warriors   357.0
12                 Punjab Kings   247.0
13             Rajasthan Royals  1348.0
14       Rising Pune Supergiant   192.0
15      Rising Pune Supergiants    53.0
16  Royal Challengers Bangalore  2449.0
17          Sunrisers Hyderabad  1020.0

In [26]:
pd.read_json('movies-250.json')

          date                                             movies
0   2022-04-03  {'Title': 'The Shawshank Redemption', 'Year': ...
1   2022-04-03  {'Title': 'The Godfather', 'Year': '1972', 'Ra...
2   2022-04-03  {'Title': 'The Dark Knight', 'Year': '2008', '...
3   2022-04-03  {'Title': 'The Godfather: Part II', 'Year': '1...
4   2022-04-03  {'Title': '12 Angry Men', 'Year': '1957', 'Rat...
..         ...                                                ...
245 2022-04-03  {'Title': 'Beauty and the Beast', 'Year': '199...
246 2022-04-03  {'Title': 'Gandhi', 'Year': '1982', 'Rated': '...
247 2022-04-03  {'Title': 'The Help', 'Year': '2011', 'Rated':...
248 2022-04-03  {'Title': 'The Handmaiden', 'Year': '2016', 'R...
249 2022-04-03  {'Title': 'Dances with Wolves', 'Year': '1990'...

[250 rows x 2 columns]

#FETCH DATA FROM API REQUEST AS a json file

In [36]:
import requests
response=requests.get('https://jsonplaceholder.typicode.com/posts/1')
response.json()['title']

'sunt aut facere repellat provident occaecati excepturi optio reprehenderit'

#WEB SCRAPING

In [53]:
import requests
from bs4 import BeautifulSoup #BeautifulSoup is a library used for web scraping
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.11'}
webpage= requests.get('https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1', headers=headers).text
#soup=BeautifulSoup(webpage,'lxml')
#print(soup.prettify())
print(response.status_code)

KeyboardInterrupt:

In [54]:
response = requests.get(
    'https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1',
    headers=headers
)

print(response.status_code)
print(response.url)
print(response.text[:1000])

KeyboardInterrupt: