<a href="https://colab.research.google.com/github/Sautramani/Pandas-Numpy/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np
import pandas as pd

In [27]:
# series from list
country=['India','pakistan','usa','nepal']
pd.Series(country)  #series is a class and we are creating the objects for this

0       India
1    pakistan
2         usa
3       nepal
dtype: object

In [28]:
# custom index
marks=[67,57,89,100]
subjects=['english','maths','sst','hindi']
pd.Series(marks,index=subjects)

english     67
maths       57
sst         89
hindi      100
dtype: int64

In [29]:
# setting a name
#pd.Series(subjects,index=marks,name='sautramani')
marks=pd.Series(subjects,index=marks,name='sautramani')
marks

67     english
57       maths
89         sst
100      hindi
Name: sautramani, dtype: object

In [30]:
#MAKE SERIES USING CSV FILES
subs=pd.read_csv('/content/subs.csv').squeeze("columns")
print(type(subs))

FileNotFoundError: [Errno 2] No such file or directory: '/content/subs.csv'

In [ ]:
df = pd.DataFrame({'A': [1, 2, 3]})
print(df)
print(df.squeeze("columns"))

In [ ]:
#import csv file having 2 columns
vk=pd.read_csv('/content/kohli_ipl.csv',index_col='match_no').squeeze("columns")
vk

In [ ]:
pd.read_csv('/content/bollywood.csv',index_col='lead').squeeze("columns")

In [ ]:
# head()-> it gives  the preview of the dataset
subs=pd.read_csv('subs.csv').squeeze("columns")
bollywood =pd.read_csv('/content/bollywood.csv',index_col='lead').squeeze("columns")
#subs.head(10)
bollywood.head()

In [ ]:
#tail()-> shows the last 5 values
subs.tail()

In [ ]:
#sample()-> returns 1 random rows from dataset
subs.sample(10)  # it shows randomness on running it many times
subs.sample(5,random_state=3) #random_state se baar baar run karne ke baad result change nahi hoga (fixes the randomness)

In [ ]:
# value_count() -> it counts frequency
bollywood.value_counts()
subs.value_counts()

In [31]:
#sort
subs.head(10)
subs.sort_values(ascending=False).head(10) #top 10  times for which max subscribers gain occured

NameError: name 'subs' is not defined

In [ ]:
subs.sort_index()

In [ ]:
#count() ->  returns  the non-missing values
#( count values which are nt NaN)
subs.count()
bollywood.count()
len(bollywood)

bollywood.isnull().sum() # to count the number of missing(NaN) values

In [ ]:
#mean
subs.mean()

In [ ]:
#dtypes
subs.dtypes
bollywood.dtypes

In [ ]:
#info()
subs.info()

In [ ]:
#statistics involving things like:count,mean,std,min
kohli=pd.read_csv("kohli_ipl.csv")
kohli.describe()

In [ ]:
#graphs
subs.plot()

In [ ]:
bollywood =pd.read_csv('/content/bollywood.csv',index_col='movie').squeeze("columns")
bollywood.value_counts().head(20).plot(kind='pie')

In [32]:
#EDITING SERIES
subs[2]=1000
subs

NameError: name 'subs' is not defined

In [ ]:
bollywood['priyanshu']="IITD"
bollywood

In [ ]:
                   #DATAFRAMES
#create dataframe using list
student=[
    [100,200,300],
    [150,250,350],
    [777,666,555]
]
pd.DataFrame(student,columns=["iq","marks","package"])

In [68]:
#using dictionary
student_dict={
    'name':['vibhu','a','b','c','d'],
    'iq':[100,200,120,888,789],
    'marks':[80,100,90,12,457],
    'package':[10,40,15,75,99]
}
students=pd.DataFrame(student_dict)
students

    name   iq  marks  package
0  vibhu  100     80       10
1      a  200    100       40
2      b  120     90       15
3      c  888     12       75
4      d  789    457       99

In [ ]:
#using read_csv
movies=pd.read_csv('/content/movies.csv')
movies

In [ ]:
ipl=pd.read_csv('/content/ipl-matches.csv')
ipl

In [33]:
#shape: Returns a tuple (rows, columns) representing DataFrame dimensions.
movies.shape

(1629, 18)

In [34]:
# Output: RangeIndex(start=0, stop=1629, step=1)
movies.index

RangeIndex(start=0, stop=1629, step=1)

In [36]:
#values: Converts the DataFrame content into a raw 2D NumPy array.
ipl.values

array([[1312200, 'Ahmedabad', '2022-05-29', ...,
        "['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312199, 'Ahmedabad', '2022-05-27', ...,
        "['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Parag', 'R Ashwin', 'TA Boult', 'YS Chahal', 'M Prasidh Krishna', 'OC McCoy']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312198, 'Kolkata', '2022-05-25', ...,
        "['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda', 'MP Stoinis', 'E Lewis', 'KH Pandya', 'PVD Chameera', 'Mohsin Khan', 'Avesh Khan', 'Ravi Bishnoi']",
        'J Madanagopal', 'MA Gough'],
       ...,
       [335984, 'Delhi', '2008-04-19', ...,
        "['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'MM Patel']",
        'Aleem Dar', 'GA Pratapkumar'],
       [335983, 'Chandigarh', '2008-04-19', ...,
        "['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'Joginder Sharma', 'P Amarnath', 'MS Gony', 'M Muralitharan']",
        'MR Benson', 'SL Shastri'],
       [335982, 'Bangalore', '2008-04-18', ...,
        "['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey', 'Mohammad Hafeez', 'LR Shukla', 'WP Saha', 'AB Agarkar', 'AB Dinda', 'M Kartik', 'I Sharma']",
        'Asad Rauf', 'RE Koertzen']], dtype=object)

In [37]:
#sample(n): Pulls $n$ random rows to get an unbiased look at data.
movies.sample(5)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1590,Deewaanapan,tt0301179,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Deewaanapan,Deewaanapan,Deewaanapan,0,2001,153,Action|Romance,4.6,378,Suraj Saxena (Arjun Rampal) lives in a remote ...,A rebel crosses swords with an influential ric...,NaN,Arjun Rampal|Dia Mirza|Vinod Khanna|Om Puri|Sm...,1 win & 2 nominations,16 November 2001 (India)
982,Jodhaa Akbar,tt0449994,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Jodhaa_Akbar,Jodhaa Akbar,Jodhaa Akbar,0,2008,213,Action|Drama|History,7.6,27541,Jodhaa Akbar is a sixteenth century love story...,A sixteenth century love story about a marriag...,NaN,Hrithik Roshan|Aishwarya Rai Bachchan|Sonu Soo...,32 wins & 21 nominations,15 February 2008 (USA)
1334,Dil Maange More,tt0328729,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dil_Maange_More,Dil Maange More!!!,Dil Maange More!!!,0,2004,123,Family|Musical|Romance,5.1,1663,Nikhil is a simple young man . He loves his ho...,Nikhil a simple naive young man twice fails ...,NaN,Shahid Kapoor|Ayesha Takia|Tulip Joshi|Soha Al...,5 nominations,31 December 2004 (India)
221,Simran (film),tt6405126,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Simran_(film),Simran,Simran,0,2017,124,Crime|Drama|Thriller,5.3,2681,A socially criticized girl who is financially ...,A socially criticized girl who is financially ...,NaN,Kangana Ranaut|Sohum Shah|Esha Tewari|Jason Lo...,1 nomination,15 September 2017 (USA)
82,My Birthday Song,tt4335954,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/My_Birthday_Song,My Birthday Song,My Birthday Song,0,2018,95,Thriller,5.5,215,After a wild night of impulse and passion adv...,After a wild night of impulse and passion adv...,NaN,Nora Fatehi|Elena Kazan|Suparna Krishna|Pitoba...,NaN,19 January 2018 (India)

In [39]:
#describe(): Generates summary statistics (mean, std, min, max, percentiles) for numerical columns.
movies.describe
ipl.describe

<bound method NDFrame.describe of           ID        City        Date   Season  MatchNumber  \
0    1312200   Ahmedabad  2022-05-29     2022        Final
1    1312199   Ahmedabad  2022-05-27     2022  Qualifier 2
2    1312198     Kolkata  2022-05-25     2022   Eliminator
3    1312197     Kolkata  2022-05-24     2022  Qualifier 1
4    1304116      Mumbai  2022-05-22     2022           70
..       ...         ...         ...      ...          ...
945   335986     Kolkata  2008-04-20  2007/08            4
946   335985      Mumbai  2008-04-20  2007/08            5
947   335984       Delhi  2008-04-19  2007/08            3
948   335983  Chandigarh  2008-04-19  2007/08            2
949   335982   Bangalore  2008-04-18  2007/08            1

                           Team1                        Team2  \
0               Rajasthan Royals               Gujarat Titans
1    Royal Challengers Bangalore             Rajasthan Royals
2    Royal Challengers Bangalore         Lucknow Super Giants
3               Rajasthan Royals               Gujarat Titans
4            Sunrisers Hyderabad                 Punjab Kings
..                           ...                          ...
945        Kolkata Knight Riders              Deccan Chargers
946               Mumbai Indians  Royal Challengers Bangalore
947             Delhi Daredevils             Rajasthan Royals
948              Kings XI Punjab          Chennai Super Kings
949  Royal Challengers Bangalore        Kolkata Knight Riders

                                          Venue                   TossWinner  \
0              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals
1              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals
2                         Eden Gardens, Kolkata         Lucknow Super Giants
3                         Eden Gardens, Kolkata               Gujarat Titans
4                      Wankhede Stadium, Mumbai          Sunrisers Hyderabad
..                                          ...                          ...
945                                Eden Gardens              Deccan Chargers
946                            Wankhede Stadium               Mumbai Indians
947                            Feroz Shah Kotla             Rajasthan Royals
948  Punjab Cricket Association Stadium, Mohali          Chennai Super Kings
949                       M Chinnaswamy Stadium  Royal Challengers Bangalore

    TossDecision SuperOver                  WinningTeam    WonBy  Margin  \
0            bat         N               Gujarat Titans  Wickets     7.0
1          field         N             Rajasthan Royals  Wickets     7.0
2          field         N  Royal Challengers Bangalore     Runs    14.0
3          field         N               Gujarat Titans  Wickets     7.0
4            bat         N                 Punjab Kings  Wickets     5.0
..           ...       ...                          ...      ...     ...
945          bat         N        Kolkata Knight Riders  Wickets     5.0
946          bat         N  Royal Challengers Bangalore  Wickets     5.0
947          bat         N             Delhi Daredevils  Wickets     9.0
948          bat         N          Chennai Super Kings     Runs    33.0
949        field         N        Kolkata Knight Riders     Runs   140.0

    method Player_of_Match                                       Team1Players  \
0      NaN       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
1      NaN      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
2      NaN      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
3      NaN       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
4      NaN   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...
..     ...             ...                                                ...
945    NaN       DJ Hussey  ['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...
946    NaN      MV Boucher  ['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...
947    NaN     MF Maharoof  ['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...
948    NaN      MEK Hussey  ['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...
949    NaN     BB McCullum  ['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...

                                          Team2Players        Umpire1  \
0    ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...    CB Gaffaney
1    ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...    CB Gaffaney
2    ['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...  J Madanagopal
3    ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...   BNJ Oxenford
4    ['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...   AK Chaudhary
..                                                 ...            ...
945  ['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...      BF Bowden
946  ['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...       SJ Davis
947  ['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...      Aleem Dar
948  ['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...      MR Benson
949  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...      Asad Rauf

            Umpire2
0       Nitin Menon
1       Nitin Menon
2          MA Gough
3         VK Sharma
4     NA Patwardhan
..              ...
945     K Hariharan
946       DJ Harper
947  GA Pratapkumar
948      SL Shastri
949     RE Koertzen

[950 rows x 20 columns]>

In [41]:
#ipl.isnull().sum()
# Shows missing values per column (e.g., City has 51 missing values)
ipl.isnull().sum()

ID                   0
City                51
Date                 0
Season               0
MatchNumber          0
Team1                0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
SuperOver            4
WinningTeam          4
WonBy                0
Margin              18
method             931
Player_of_Match      4
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64

In [42]:
#duplicated(): Identifies duplicate rows. Chain with .sum() to count total complete duplicates.
movies.duplicated().sum()

np.int64(0)

In [53]:
  #MATHEMATICAL METHODS
students.sum(axis=1) #row wise

0     190
1     340
2     225
3     975
4    1345
dtype: int64

In [56]:
#Apply min, max, mean on single columns
students['marks'].mean()

np.float64(147.8)

In [54]:
students.min() # columnwise min

iq         100
marks       12
package     10
dtype: int64

In [58]:
#fetching multiple columns
movies[['title_x','year_of_release','actors']]

,title_x,year_of_release,actors
0,Uri: The Surgical Strike,2019,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
1,Battalion 609,2019,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
2,The Accidental Prime Minister (film),2019,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
3,Why Cheat India,2019,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...
4,Evening Shadows,2018,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...
...,...,...,...
1624,Tera Mera Saath Rahen,2001,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...
1625,Yeh Zindagi Ka Safar,2001,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...
1626,Sabse Bada Sukh,2018,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...
1627,Daaka,2019,Gippy Grewal|Zareen Khan|
1628,Humsafar,2011,Fawad Khan|

In [62]:
 #fetching rows and multiple rows using
 #iloc-> searches using index positions
 #loc-> searches using index labels
 movies.iloc[0]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [65]:
movies.iloc[[0,4,7]]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
7,Bombairiya,tt4971258,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bombairiya,Bombairiya,Bombairiya,0,2019,104,Comedy|Crime|Drama,4.3,295,It follows the story of Meghna who gets embro...,It follows the story of Meghna who gets embro...,They didn't mean to change the world.,Radhika Apte|Akshay Oberoi|Siddhanth Kapoor|Ra...,NaN,18 January 2019 (India)

In [81]:
#loc
student_dict={
    'name':['vibhu','a','b','c','d'],
    'iq':[100,200,120,888,789],
    'marks':[80,100,90,12,457],
    'package':[10,40,15,75,99]
}
students=pd.DataFrame(student_dict)
students
students.loc[1] # return  row whose index label is 1.

name         a
iq         200
marks      100
package     40
Name: 1, dtype: object

In [79]:
# loc for rows+columns
movies.iloc[0:3,0:3]
movies.loc[0:2,'title_x':'poster_path']

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...